// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package smartassistent

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceReq) Reset()         { *m = DeviceReq{} }
func (m *DeviceReq) String() string { return proto.CompactTextString(m) }
func (*DeviceReq) ProtoMessage()    {}
func (*DeviceReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *DeviceReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceReq.Unmarshal(m, b)
}
func (m *DeviceReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceReq.Marshal(b, m, deterministic)
}
func (m *DeviceReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceReq.Merge(m, src)
}
func (m *DeviceReq) XXX_Size() int {
	return xxx_messageInfo_DeviceReq.Size(m)
}
func (m *DeviceReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceReq proto.InternalMessageInfo

func (m *DeviceReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Device TODO 补充详细字段
type Device struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	Event                string   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// TODO 需要确定对应的json
// 1）发现设备回调；
// 2）状态变更回调；
type Response struct {
	Body                 []byte   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceReq)(nil), "smartassistent.DeviceReq")
	proto.RegisterType((*Device)(nil), "smartassistent.Device")
	proto.RegisterType((*Request)(nil), "smartassistent.Request")
	proto.RegisterType((*Response)(nil), "smartassistent.Response")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x51, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0x71, 0x57, 0x3b, 0x2c, 0xfb, 0x30, 0x88, 0xd6, 0x15, 0x44, 0xf2, 0xb4, 0x0f,
	0x52, 0xc4, 0x1e, 0x40, 0xa8, 0xe2, 0x01, 0xe2, 0x09, 0x52, 0x33, 0x48, 0xc0, 0x24, 0x6d, 0x33,
	0x2d, 0x78, 0x07, 0x0f, 0x2d, 0xa6, 0x45, 0xb0, 0xf6, 0xed, 0x4f, 0xbe, 0xf9, 0x67, 0xf8, 0x7f,
	0xd8, 0xb5, 0x1f, 0xc3, 0xbb, 0xf5, 0x65, 0xdb, 0x07, 0x0e, 0xb8, 0x8f, 0x4e, 0xf7, 0xac, 0x63,
	0xb4, 0x91, 0xc9, 0xb3, 0xbc, 0x86, 0xfc, 0x99, 0x46, 0xfb, 0x46, 0x8a, 0x3a, 0xdc, 0x43, 0x66,
	0x4d, 0x21, 0x6e, 0xc5, 0x31, 0x57, 0x99, 0x35, 0xf2, 0x0e, 0xb6, 0x13, 0x5c, 0x12, 0x44, 0x38,
	0xf1, 0xda, 0x51, 0x91, 0xa5, 0x9f, 0xa4, 0x65, 0x05, 0xa7, 0x8a, 0xba, 0x81, 0x22, 0xe3, 0x39,
	0x6c, 0x68, 0x24, 0xcf, 0xb3, 0x63, 0x7a, 0xfc, 0x98, 0x9a, 0x60, 0x3e, 0x93, 0x69, 0xa7, 0x92,
	0x96, 0x37, 0x70, 0xa6, 0x28, 0xb6, 0xc1, 0x47, 0x5a, 0xe3, 0x0f, 0x5f, 0x02, 0x36, 0x4f, 0xc1,
	0x11, 0x63, 0x0d, 0x79, 0x6d, 0xcd, 0x2b, 0xf7, 0xa4, 0x1d, 0x5e, 0x96, 0x7f, 0x73, 0x94, 0xf3,
	0xe5, 0x43, 0xf1, 0x1f, 0x4c, 0xdb, 0x8f, 0xe2, 0x5e, 0xe0, 0x23, 0xc0, 0x8b, 0xf5, 0x66, 0x0e,
	0x75, 0xb5, 0x9c, 0xfd, 0x6d, 0xe2, 0x70, 0xb1, 0x8e, 0x9a, 0x6d, 0x6a, 0xb1, 0xfa, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0xd9, 0x93, 0x89, 0x33, 0x55, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CometClient is the client API for Comet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CometClient interface {
	BidStream(ctx context.Context, opts ...grpc.CallOption) (Comet_BidStreamClient, error)
	FindDevice(ctx context.Context, in *DeviceReq, opts ...grpc.CallOption) (*Device, error)
}

type cometClient struct {
	cc *grpc.ClientConn
}

func NewCometClient(cc *grpc.ClientConn) CometClient {
	return &cometClient{cc}
}

func (c *cometClient) BidStream(ctx context.Context, opts ...grpc.CallOption) (Comet_BidStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Comet_serviceDesc.Streams[0], "/smartassistent.Comet/BidStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &cometBidStreamClient{stream}
	return x, nil
}

type Comet_BidStreamClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type cometBidStreamClient struct {
	grpc.ClientStream
}

func (x *cometBidStreamClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cometBidStreamClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cometClient) FindDevice(ctx context.Context, in *DeviceReq, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := c.cc.Invoke(ctx, "/smartassistent.Comet/FindDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CometServer is the server API for Comet service.
type CometServer interface {
	BidStream(Comet_BidStreamServer) error
	FindDevice(context.Context, *DeviceReq) (*Device, error)
}

func RegisterCometServer(s *grpc.Server, srv CometServer) {
	s.RegisterService(&_Comet_serviceDesc, srv)
}

func _Comet_BidStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CometServer).BidStream(&cometBidStreamServer{stream})
}

type Comet_BidStreamServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type cometBidStreamServer struct {
	grpc.ServerStream
}

func (x *cometBidStreamServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cometBidStreamServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Comet_FindDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CometServer).FindDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smartassistent.Comet/FindDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CometServer).FindDevice(ctx, req.(*DeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Comet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "smartassistent.Comet",
	HandlerType: (*CometServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindDevice",
			Handler:    _Comet_FindDevice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidStream",
			Handler:       _Comet_BidStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}
