# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: plugin.proto for package 'comet'

require 'grpc'
require 'plugin_pb'

module Comet
  module Comet
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'comet.Comet'

      rpc :BidStream, stream(::Comet::Request), stream(::Comet::Response)
    end

    Stub = Service.rpc_stub_class
  end
end
