# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("plugin.proto", :syntax => :proto3) do
    add_message "comet.Request" do
      optional :body, :bytes, 1
    end
    add_message "comet.Response" do
      optional :body, :bytes, 1
    end
  end
end

module Comet
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("comet.Request").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("comet.Response").msgclass
end
